/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Mateus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastrarFuncionario = new javax.swing.JMenu();
        CMinhatura = new javax.swing.JMenuItem();
        Cminhtura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        MenuCadastrarFuncionario.setText("Cadastrar");
        MenuCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CMinhatura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CMinhatura.setText("Cadastrar Funcionario");
        CMinhatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMinhaturaActionPerformed(evt);
            }
        });
        MenuCadastrarFuncionario.add(CMinhatura);

        Cminhtura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cminhtura.setText("Cadastrar Minhaturas");
        Cminhtura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CminhturaActionPerformed(evt);
            }
        });
        MenuCadastrarFuncionario.add(Cminhtura);

        jMenuBar1.add(MenuCadastrarFuncionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMinhaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMinhaturaActionPerformed
        
        Cadastrar tela = new Cadastrar();
        tela.setTitle("Cadastro de Funcionario");
        tela.setVisible(true);
        
    }//GEN-LAST:event_CMinhaturaActionPerformed

    private void CminhturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CminhturaActionPerformed
       CadastrarMinhaturas tela = new CadastrarMinhaturas();
       tela.setTitle("Cadstro de minhaturas");
       tela.setVisible(true);
    }//GEN-LAST:event_CminhturaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CMinhatura;
    private javax.swing.JMenuItem Cminhtura;
    private javax.swing.JMenu MenuCadastrarFuncionario;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
