/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Mateus
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemBrasileirosCadastrar = new javax.swing.JMenuItem();
        MenuItemBrasileiroListar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemAmericanosCadastrar = new javax.swing.JMenuItem();
        MenuItemAmericanosListar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemCaminhoesCadastrar = new javax.swing.JMenuItem();
        MenuItemCaminhoesListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jMenu1.setText("Carrinhos Brasileiros ");

        MenuItemBrasileirosCadastrar.setText("Cadastrar");
        jMenu1.add(MenuItemBrasileirosCadastrar);

        MenuItemBrasileiroListar.setText("Listar");
        jMenu1.add(MenuItemBrasileiroListar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carrinhos americanos");

        MenuItemAmericanosCadastrar.setText("Cadastrar");
        jMenu2.add(MenuItemAmericanosCadastrar);

        MenuItemAmericanosListar.setText("Listar");
        jMenu2.add(MenuItemAmericanosListar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Caminhões ");

        MenuItemCaminhoesCadastrar.setText("Cadastrar");
        jMenu3.add(MenuItemCaminhoesCadastrar);

        MenuItemCaminhoesListar.setText("Listar");
        jMenu3.add(MenuItemCaminhoesListar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAmericanosCadastrar;
    private javax.swing.JMenuItem MenuItemAmericanosListar;
    private javax.swing.JMenuItem MenuItemBrasileiroListar;
    private javax.swing.JMenuItem MenuItemBrasileirosCadastrar;
    private javax.swing.JMenuItem MenuItemCaminhoesCadastrar;
    private javax.swing.JMenuItem MenuItemCaminhoesListar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
